/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample.web2;

import java.io.IOException;
import java.io.Serializable;

import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.faces.context.Flash;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;

@Named
@RequestScoped
public class Index implements Serializable {

    private String hoge;

    public String init() {

        HttpServletRequest req = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext()
                .getRequest();
        req.getParameterMap();

        System.out.println(req.getParameter("key"));


        Flash flash = FacesContext.getCurrentInstance().getExternalContext().getFlash();
        System.out.println(flash.get("aaa"));

        return null;
    }

    public String redirect() throws IOException {

        FacesContext.getCurrentInstance().getExternalContext()
                .dispatch("http://localhost:8080/sample-web1/index.xhtml");
        return null;
    }

    public String submit() throws IOException {
        return null;
    }

    public String getHoge() {
        return hoge;
    }

    public void setHoge(String hoge) {
        this.hoge = hoge;
    }
}
