/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample.web1;

import java.io.Serializable;

import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.faces.context.Flash;
import javax.inject.Named;

@Named
@RequestScoped
public class Index2 implements Serializable {

    public String init() {

        Flash flash = FacesContext.getCurrentInstance().getExternalContext().getFlash();
        System.out.println(flash.get("aaa"));

        return null;
    }

}
