/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample.web1;

import java.io.IOException;
import java.io.Serializable;

import javax.enterprise.context.RequestScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.context.Flash;
import javax.inject.Named;

@Named
@RequestScoped
public class Index implements Serializable {

    public String init() {

        System.out
                .println(FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get("aiueo"));

        return null;
    }

    public String redirect() throws IOException {

        Flash flash = FacesContext.getCurrentInstance().getExternalContext().getFlash();
        flash.put("aaa", "aaaaa");

        ExternalContext exCtx = FacesContext.getCurrentInstance().getExternalContext();
        exCtx.redirect("http://localhost:8080/sample-web2/index.xhtml?key=value");

        return null;
    }

    public String redirect2() throws IOException {

        Flash flash = FacesContext.getCurrentInstance().getExternalContext().getFlash();
        flash.put("aaa", "aaaaa");

        return "index2?faces-redirect=true";
    }
}
